name: bs58check
description: A straight forward implementation of base58check extending upon bs58 for Flutter writing in Dart.
version: 1.0.1
homepage: https://github.com/anicdh
author: andoan <anicdh@gmail.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  hex: # ^0.1.2 - DONE: secure code reviewed 6afb93f
    git:
      url: git://github.com/KomodoPlatform/dart-hex.git
      ref: 6afb93fbe9024b174bf7075338e7ca0fe9c0411b
  crypto: ^2.0.3 # dart.dev
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0 # dart.dev
